# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1fc53a9dff8e035caab913839a4da7fcbb9f95be97dec4156b10a855845498f230044267e1295a9c1946c50b275d41482f7dc3757a34ed12ad36d6cb84e29fc7

test:
  secret_key_base: 70f9f2aac5bd4f6c726dc3f4d532f8c35b866de2d2e803e29f3a449403f420380d964809618f9dc33b419037993e04fe665915336ece576a96b565dbf2c35705

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
